config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :team_member_of_teams
  resources :member_of_teams, only: [:index, :show, :create, :update, :destroy]
  resources :marathon_questions
  resources :questions, only: [:index, :show, :create, :update, :destroy]
  resources :marathon_teams
  resources :teams, only: [:index, :show, :create, :update, :destroy]
  resources :marathons, only: [:index, :show, :create, :update, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'remove_questions' => 'marathon_questions#removeQuestions', via: :delete
  match 'remove_teams' => 'marathon_teams#removeTeams', via: :delete
  match 'remove_members' => 'team_member_of_teams#removeMembers', via: :delete
  root to: 'application#angular'
end

app/models/team_member_of_team.rb
class TeamMemberOfTeam < ApplicationRecord
  belongs_to :team
  belongs_to :member_of_team
end

app/controllers/team_member_of_teams_controller.rb
class TeamMemberOfTeamsController < ApplicationController
  before_action :set_team_member_of_team, only: [:show, :edit, :update, :destroy]

  # GET /team_member_of_teams
  # GET /team_member_of_teams.json
  def index
    @team_member_of_teams = TeamMemberOfTeam.all
  end

  # GET /team_member_of_teams/1
  # GET /team_member_of_teams/1.json
  def show
  end

  # GET /team_member_of_teams/new
  def new
    @team_member_of_team = TeamMemberOfTeam.new
  end

  # GET /team_member_of_teams/1/edit
  def edit
  end

  # POST /team_member_of_teams
  # POST /team_member_of_teams.json
  def create
    @team_member_of_team = TeamMemberOfTeam.new(team_member_of_team_params)

    respond_to do |format|
      if @team_member_of_team.save
        format.html { redirect_to @team_member_of_team, notice: 'Team member of team was successfully created.' }
        format.json { render :show, status: :created, location: @team_member_of_team }
      else
        format.html { render :new }
        format.json { render json: @team_member_of_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_member_of_teams/1
  # PATCH/PUT /team_member_of_teams/1.json
  def update
    respond_to do |format|
      if @team_member_of_team.update(team_member_of_team_params)
        format.html { redirect_to @team_member_of_team, notice: 'Team member of team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member_of_team }
      else
        format.html { render :edit }
        format.json { render json: @team_member_of_team.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def removeMembers
    @team_member_of_team = TeamMemberOfTeam.find_by(team_id: params[:team_id], member_of_team_id: params[:member_of_team_id])
    @team_member_of_team.destroy
  end

  # DELETE /team_member_of_teams/1
  # DELETE /team_member_of_teams/1.json
  def destroy
    @team_member_of_team.destroy
    respond_to do |format|
      format.html { redirect_to team_member_of_teams_url, notice: 'Team member of team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member_of_team
      @team_member_of_team = TeamMemberOfTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_of_team_params
      params.require(:team_member_of_team).permit(:team_id, :member_of_team_id)
    end
end

app/helpers/team_member_of_teams_helper.rb
module TeamMemberOfTeamsHelper
end

app/views/team_member_of_teams/_form.html.erb
<%= form_for(team_member_of_team) do |f| %>
  <% if team_member_of_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_member_of_team.errors.count, "error") %> prohibited this team_member_of_team from being saved:</h2>

      <ul>
      <% team_member_of_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="field">
    <%= f.label :member_of_team_id %>
    <%= f.text_field :member_of_team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_member_of_teams/edit.html.erb
<h1>Editing Team Member Of Team</h1>

<%= render 'form', team_member_of_team: @team_member_of_team %>

<%= link_to 'Show', @team_member_of_team %> |
<%= link_to 'Back', team_member_of_teams_path %>

app/views/team_member_of_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Member Of Teams</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Member of team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_member_of_teams.each do |team_member_of_team| %>
      <tr>
        <td><%= team_member_of_team.team %></td>
        <td><%= team_member_of_team.member_of_team %></td>
        <td><%= link_to 'Show', team_member_of_team %></td>
        <td><%= link_to 'Edit', edit_team_member_of_team_path(team_member_of_team) %></td>
        <td><%= link_to 'Destroy', team_member_of_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Member Of Team', new_team_member_of_team_path %>

app/views/team_member_of_teams/new.html.erb
<h1>New Team Member Of Team</h1>

<%= render 'form', team_member_of_team: @team_member_of_team %>

<%= link_to 'Back', team_member_of_teams_path %>

app/views/team_member_of_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_member_of_team.team %>
</p>

<p>
  <strong>Member of team:</strong>
  <%= @team_member_of_team.member_of_team %>
</p>

<%= link_to 'Edit', edit_team_member_of_team_path(@team_member_of_team) %> |
<%= link_to 'Back', team_member_of_teams_path %>