config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :team_member_of_teams
  resources :member_of_teams, only: [:index, :show, :create, :update, :destroy]
  resources :marathon_questions
  resources :questions, only: [:index, :show, :create, :update, :destroy]
  resources :marathon_teams
  resources :teams, only: [:index, :show, :create, :update, :destroy]
  resources :marathons, only: [:index, :show, :create, :update, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match 'remove_questions' => 'marathon_questions#removeQuestions', via: :delete
  match 'remove_teams' => 'marathon_teams#removeTeams', via: :delete
  match 'remove_members' => 'team_member_of_teams#removeMembers', via: :delete
  root to: 'application#angular'
end

app/models/marathon_question.rb
class MarathonQuestion < ApplicationRecord
  belongs_to :marathon
  belongs_to :question
end

app/controllers/marathon_questions_controller.rb
class MarathonQuestionsController < ApplicationController
  before_action :set_marathon_question, only: [:show, :edit, :update, :destroy]

  # GET /marathon_questions
  # GET /marathon_questions.json
  def index
    @marathon_questions = MarathonQuestion.all
  end

  # GET /marathon_questions/1
  # GET /marathon_questions/1.json
  def show
  end

  # GET /marathon_questions/new
  def new
    @marathon_question = MarathonQuestion.new
  end

  # GET /marathon_questions/1/edit
  def edit
  end

  # POST /marathon_questions
  # POST /marathon_questions.json
  def create
    @marathon_question = MarathonQuestion.new(marathon_question_params)

    respond_to do |format|
      if @marathon_question.save
        format.html { redirect_to @marathon_question, notice: 'Marathon question was successfully created.' }
        format.json { render :show, status: :created, location: @marathon_question }
      else
        format.html { render :new }
        format.json { render json: @marathon_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marathon_questions/1
  # PATCH/PUT /marathon_questions/1.json
  def update
    respond_to do |format|
      if @marathon_question.update(marathon_question_params)
        format.html { redirect_to @marathon_question, notice: 'Marathon question was successfully updated.' }
        format.json { render :show, status: :ok, location: @marathon_question }
      else
        format.html { render :edit }
        format.json { render json: @marathon_question.errors, status: :unprocessable_entity }
      end
    end
  end

  def removeQuestions
    @marathon_question = MarathonQuestion.find_by(marathon_id: params[:marathon_id], question_id: params[:question_id])
    @marathon_question.destroy
  end

  # DELETE /marathon_questions/1
  # DELETE /marathon_questions/1.json
  def destroy
    @marathon_question.destroy
    respond_to do |format|
      format.html { redirect_to marathon_questions_url, notice: 'Marathon question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marathon_question
      @marathon_question = MarathonQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marathon_question_params
      params.require(:marathon_question).permit(:marathon_id, :question_id)
    end
end

app/helpers/marathon_questions_helper.rb
module MarathonQuestionsHelper
end

app/views/marathon_questions/_form.html.erb
<%= form_for(marathon_question) do |f| %>
  <% if marathon_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marathon_question.errors.count, "error") %> prohibited this marathon_question from being saved:</h2>

      <ul>
      <% marathon_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marathon_id %>
    <%= f.text_field :marathon_id %>
  </div>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.text_field :question_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marathon_questions/edit.html.erb
<h1>Editing Marathon Question</h1>

<%= render 'form', marathon_question: @marathon_question %>

<%= link_to 'Show', @marathon_question %> |
<%= link_to 'Back', marathon_questions_path %>

app/views/marathon_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marathon Questions</h1>

<table>
  <thead>
    <tr>
      <th>Marathon</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marathon_questions.each do |marathon_question| %>
      <tr>
        <td><%= marathon_question.marathon %></td>
        <td><%= marathon_question.question %></td>
        <td><%= link_to 'Show', marathon_question %></td>
        <td><%= link_to 'Edit', edit_marathon_question_path(marathon_question) %></td>
        <td><%= link_to 'Destroy', marathon_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marathon Question', new_marathon_question_path %>

app/views/marathon_questions/new.html.erb
<h1>New Marathon Question</h1>

<%= render 'form', marathon_question: @marathon_question %>

<%= link_to 'Back', marathon_questions_path %>

app/views/marathon_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marathon:</strong>
  <%= @marathon_question.marathon %>
</p>

<p>
  <strong>Question:</strong>
  <%= @marathon_question.question %>
</p>

<%= link_to 'Edit', edit_marathon_question_path(@marathon_question) %> |
<%= link_to 'Back', marathon_questions_path %>